### ISSUE TITLE
Problems running under VMware

### ISSUE THREAD

**Issue by beevik** [macmade/XEOS#2]
When launching the XEOS operating system using VMware workstation v11.1.3 (on Linux), the XEOS kernel locks up during the following step:

```
[ XEOS ]> Registering the keyboard IRQ:
```

When I then press a key, I get the following error message:

```
[ XEOS ]> A fatal error occured - Please reboot your computer
```

The problem occurs with both 32-bit and 64-bit virtual machines.

I haven't had a chance to fully debug the problem yet, but I wondered if you might have seen a similar issue in the past.

(You write beautiful code, by the way.)

**Comment by macmade** [comment]
Hi,

Thanks a lot. : )

Long time since I've last tested this with VMWare.
I usually run XEOS with VirtualBox.

I'll try to test this asap. I'll get back to you... : )

**Comment by beevik** [comment]
Thanks. Here's the link to download the free version of VMware workstation player 12 in case you don't already have it:

https://my.vmware.com/web/vmware/free#desktop_end_user_computing/vmware_workstation_player/12_0

The link is a little hard to find on the vmware web site.

**Comment by macmade** [comment]
Thanks, I'll try that... : )
